#! /bin/sh
export DIFF_OPTIONS="-s -W -B"

printf "Test 1:\n"
cat ./santorini.rc/1-in.json | ./xrun | sdiff ./santorini.rc/1-out.json - $DIFF_OPTIONS

printf "Test 2:\n"
cat ./santorini.rc/2-in.json | ./xrun | sdiff ./santorini.rc/2-out.json - $DIFF_OPTIONS

printf "Test 3:\n"
cat ./santorini.rc/3-in.json | ./xrun | sdiff ./santorini.rc/3-out.json - $DIFF_OPTIONS

printf "Test 4:\n"
cat ./santorini.rc/4-in.json | ./xrun | sdiff ./santorini.rc/4-out.json - $DIFF_OPTIONS

printf "\nTests Completed for XTournament. Any differences displayed above.\n"