#! /bin/sh
export DIFF_OPTIONS="-s -W -B"

printf "Test 1:"
cat ./board-tests/1-in.json | ./xboard | sdiff ./board-tests/1-out.json $DIFF_OPTIONS -

printf "\nTest 2:"
cat ./board-tests/2-in.json | ./xboard | sdiff ./board-tests/2-out.json $DIFF_OPTIONS -

printf "\nTest 3:"
cat ./board-tests/3-in.json | ./xboard | sdiff ./board-tests/3-out.json $DIFF_OPTIONS -

printf "\nTest 4:"
cat ./board-tests/4-in.json | ./xboard | sdiff ./board-tests/4-out.json $DIFF_OPTIONS -

printf "\nTest 5:"
cat ./board-tests/5-in.json | ./xboard | sdiff ./board-tests/5-out.json $DIFF_OPTIONS -

printf "\nTests Completed for XBoard. Any differences displayed above.\n"