#! /bin/sh
export DIFF_OPTIONS="-s -W -B"

printf "Test 2:"
cat ./board-tests/2-in.json | ./xboard | sdiff ./board-tests/2-out.json $DIFF_OPTIONS -

printf "\nTest 3:"
cat ./board-tests/3-in.json | ./xboard | sdiff ./board-tests/3-out.json $DIFF_OPTIONS -

printf "\nTests Completed for XBoard. Any differences displayed above.\n"