#! /bin/sh
export DIFF_OPTIONS="-s -W -B"
printf "Test 2:"
cat ./rules-tests/2-in.json | ./xrules | sdiff ./rules-tests/2-out.json - $DIFF_OPTIONS

printf "\nTest 3:"
cat ./rules-tests/3-in.json | ./xrules | sdiff ./rules-tests/3-out.json - $DIFF_OPTIONS

printf "\nTests Completed for XRules. Any differences displayed above.\n"