#! /bin/sh
export DIFF_OPTIONS="-s -W -B"

printf "Test 2:"
cat ./strategy-tests/2-in.json | ./xstrategy | sdiff ./strategy-tests/2-out.json - $DIFF_OPTIONS

printf "\nTest 3:"
cat ./strategy-tests/3-in.json | ./xstrategy | sdiff ./strategy-tests/3-out.json - $DIFF_OPTIONS

printf "\nTest 4:"
cat ./strategy-tests/4-in.json | ./xstrategy | sdiff ./strategy-tests/4-out.json - $DIFF_OPTIONS

printf "\nTests Completed for XStrategy. Any differences displayed above.\n"